{%- macro remove_stopwords(column) -%}
    {% set stopwords = (
        "the",
        "of",
        "to",
        "in",
        "for",
        "is",
        "on",
        "it",
        "at",
        "or",
        "don",
        "png",
        "http",
        "https",
        "reddit",
        "redd",
        "that",
        "by",
        "with",
        "this",
        "be",
        "www",
        "are",
        "as",
        "i",
        "you",
        "from",
        "a",
        "com",
        "an",
        "about",
        "was",
        "edu",
        "who",
        "what",
        "where",
        "when",
        "why",
        "how",
        "which",
        "en",
        "&",
        "*",
        "and",
    ) %}
    where {{ column }} not in {{ stopwords }}
{%- endmacro -%}
